site_name: FuseML docs
theme:
  name: material
  palette:
    primary: green
    accent: cyan
repo_url: https://github.com/fuseml/docs
edit_uri: edit/main/docs/

# TODO: Validate with our legal team.
copyright: "Copyright &copy; 2021 FuseML Author(s)"
